image: rust

pipelines:
  default:
    - step:
        name: Build
        caches:
          - cargo
          - rust-target
        script:
          - echo "Installing pre-requisites"        ; apt-get update && apt-get install -y gcc-mingw-w64-x86-64
          - echo "Adding rust targets"              ; rustup target add x86_64-pc-windows-gnu
          - echo "Build for x86_64-pc-windows-gnu"  ; cargo build --release --target x86_64-pc-windows-gnu
        artifacts:
          - target/x86_64-pc-windows-gnu/release/coap-cli.exe
    - step:
        name: Deploy
        trigger: manual
        script:
          - pipe: atlassian/bitbucket-upload-file:0.7.5
            variables:
              BITBUCKET_ACCESS_TOKEN: $BITBUCKET_ACCESS_TOKEN
              FILENAME: "target/x86_64-pc-windows-gnu/release/coap-cli.exe"

definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target
