image: rust

pipelines:
  default:
    - step:
        caches:
          - cargo
          - rust-target
        script:
          - echo "Installing pre-requisites"        ; apt-get update && apt-get install -y gcc-mingw-w64-x86-64
          - echo "Build for x86_64-pc-windows-gnu"  ; cargo build --release --target x86_64-pc-windows-gnu
        artifacts:
          - target/x86_64-pc-windows-gnu/release/coap-cli.exe

definitions:
  caches:
    cargo: /usr/local/cargo # CARGO_HOME
    rust-target: $BITBUCKET_CLONE_DIR/target
