name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo
        id: cache-cargo
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
      - name: Build
        run: cargo build --verbose --release
      - name: Upload binary
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: coap-cli-linux-x64
          path: target/release/coap-cli
      - name: Upload binary
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: coap-cli-windows-x64
          path: target/release/coap-cli.exe
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist/binaries
      - name: Display structure of downloaded files
        run: ls -R dist/binaries
      - name: Create distribution archives
        run: |
          mkdir -p dist/archives
          tar -zcf dist/archives/coap-cli-linux-x64-${{ github.ref_name }}.tgz -C dist/binaries/coap-cli-linux-x64 *
          zip -j dist/archives/coap-cli-windows-x64-${{ github.ref_name }}.zip dist/binaries/coap-cli-windows-x64/*
      - name: Display structure of distribution files
        run: ls -lR dist/archives
